modLoader="javafml"
loaderVersion="${loaderRange}"
license="MIT"

[[mods]]
modId="skin_switching"
version="${modVersion}"
displayName="Skin Switching"
authors="幼幼紫"
description='''输入正版玩家名，轻松切换皮肤，支持本地显示与联机同步。'''
logoFile="logo.png"
logoBlur=false

[[mixins]]
config="skin_switching.mixins.json"

[[dependencies.skin_switching]]
modId="neoforge"
type="required"
versionRange="${neoRange}"
ordering="NONE"
side="BOTH"

[[dependencies.skin_switching]]
modId="minecraft"
type="required"
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"
