modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="skin_switching"
version="0.1.1"
displayName="Skin Switching"
authors="幼幼紫"
description='''输入正版玩家名，轻松切换皮肤，支持本地显示与联机同步。'''
logoFile="logo.png"
logoBlur=false

[[mixins]]
config="skin_switching.mixins.json"

[[dependencies.skin_switching]]
modId="neoforge"
type="required"
versionRange="[21.1.251,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.skin_switching]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
